//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nico_carServiceEntities : DbContext
    {
        public nico_carServiceEntities()
            : base("name=nico_carServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Part> Part { get; set; }
        public virtual DbSet<Part_Inventorry> Part_Inventorry { get; set; }
        public virtual DbSet<Purchase_Queue> Purchase_Queue { get; set; }
        public virtual DbSet<Service> Service { get; set; }
    }
}
