//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nicoEntities2 : DbContext
    {
        public nicoEntities2()
            : base("name=nicoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Salon> Salon { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<ShopZapchast> ShopZapchast { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<SkladZapch> SkladZapch { get; set; }
        public virtual DbSet<Zapchast> Zapchast { get; set; }
    }
}
