//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Queue
    {
        public int Purchase_Queue_ID { get; set; }
        public int Part_ID { get; set; }
        public int Quantity { get; set; }
        public int Days_to_arrive { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
