//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int ID_Purchase { get; set; }
        public int ID_Detail { get; set; }
        public int Quantity { get; set; }
        public double Total_price { get; set; }
        public int Days_to_arrival { get; set; }
    
        public virtual Detail Detail { get; set; }
    }
}
