//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkladZapch
    {
        public int ID_SkladZapch { get; set; }
        public int ID_Sklad { get; set; }
        public int ID_Zapchast { get; set; }
    
        public virtual Sklad Sklad { get; set; }
        public virtual Zapchast Zapchast { get; set; }
    }
}
